name: build_windows

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Version tag"
        required: true
        default: "v0.1.0"

jobs:
  release:
    name: Build And Release Windows

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    # create steps
    steps:
      # step1: check out repository
      - name: Check out git repository
        uses: actions/checkout@v2

      # step2: install node env
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 18

      # step3: npm install
      - name: npm install
        run: |
          npm install -g phantomjs-prebuilt
          npm install

      # step4: build app
      - name: build windows app
        run: |
          npm run win
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # step5: create release
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          body: "Release ${{ github.event.inputs.tag }}"
          files: "dist/*.exe"
          token: ${{ secrets.GITHUB_TOKEN }}
