name: sync_gitee

on:
  release:
    types: [published]

jobs:
  build:
    name: sync_gitee
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runs-on: [ubuntu-latest]

    steps:
      - name: gitee release
        id: gitee_release
        uses: h-twinkle/sync-action@v1.0
        with:
          gitee_owner: xrj4j_admin
          gitee_repo: assist_3d
          gitee_token: ${{ secrets.GITEE_TOKEN }}
          github_owner: Tiane-ira
          github_repo: assist_3d
          gitee_upload_retry_times: 3
