name: sync_gitee

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Version tag"
        required: true
        default: "v0.1.0"

jobs:
  release:
    name: Build And Release Windows

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: gitee release
        id: create_release
        uses: h-twinkle/sync-action@v1.0
        with:
          gitee_owner: xrj4j_admin
          gitee_repo: assist_3d
          gitee_token: ${{ secrets.GITEE_TOKEN }}
          github_owner: Tiane-ira
          github_repo: assist_3d
          gitee_upload_retry_times:  3
